#imagem Python oficial como base
FROM python:3.8

# Script python
COPY adm.py /app/


#diretório de trabalho no contêiner
WORKDIR /app/



# Comando padrão para executar scripts
CMD ["python", "adm.py"]
